# Generated by Django 6.1.1 on 2026-09-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='password',
            field=models.CharField(default='123456', max_length=100),
            preserve_default=False,
        ),
    ]
