# Generated by Django 6.1.1 on 2026-09-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0003_buyer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='delivery_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
