# Generated by Django 6.1.1 on 2026-10-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0004_contract_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
